#datset
w_size: 7
stride: 7
dilate: 2

#model cofign
d_model: 128
nhead: 8
d_att: 64
layer_num: 3
weight_decay: 0.01
dp_rate: 0.2


#data_config
benchmark: xsub
view: joint
label_num: 60

#data loader
batch_size: 64
accum_iter: 4
workers: 8

# training
eval_step: 1000
train_step: 50000
log_pth: ./training_log/pre_train/NTU_60

warmup_steps: 1000
lr: 0.0004
lr_end: 0.000002
lr_gamma: 0.1


#loss weight
s_pose_w: 1
c_motion_w: 1
v_motion_w: 1
last_cx_w: 1
